### ISSUE TITLE
Research how to set up oracle data for pairs

### ISSUE THREAD

**Issue by boivlad** [yozh-io/lenbow-core#3]
- How to set up oracle data for pairs?
- How work calldata in exist pairs in Kashi?

**Comment by AntonHl** [comment]
currently existing oracle data works fine, for example for contract at https://polygonscan.com/address/0x97D7C8AD06d08635358A35e9862adBe2727c2340#code
oracleData is 0x000000000000000000000000f9d5aac6e5572aefa6bd64108ff86a222f69b64d000000000000000000000000327e23a4855b6f663a28c5161541d69af897330200000000000000000000000000000000000000000000000000000000000f4240
which decode into this object 
{
  "0": "0xf9d5AAC6E5572AEFa6bd64108ff86a222F69B64d",
  "1": "0x327e23A4855b6F663a28c5161541d69Af8973302",
  "2": {
    "_hex": "0x0f4240" ///1000000
  }
}
and for other contract which is reversed data decode into 
{
  "0": "0x327e23A4855b6F663a28c5161541d69Af8973302",
  "1": "0xf9d5AAC6E5572AEFa6bd64108ff86a222F69B64d",
  "2": {
    "_hex": "0x0c9f2c9cd04674edea40000000"//10**30
  }
}
with this data get method of oracle works fine
